### PR TITLE
OSX build fixes

### PR DESCRIPTION
**Pull request by eapache**
@BrianAker see the commit messages for more details on each fix. I've not really worked with bison or libmemcached before, so I'm only 50/50 that these fixes are correct, but they seem to work for me. Happy to make changes if what I've got here isn't quite right.

cc @ndurks

### CODE REVIEW

**Comment by BrianAker** [comment]
I use the bison from "brew install bison", the version of Bison that ships with OS X is ancient.   ( I should probably add a warning for that. )
I haven't looked at your changes yet.

**Comment by BrianAker** [comment]
And just for reference, my bison:
$ bison --version
bison (GNU Bison) 3.7.2

**Comment by eapache** [comment]
Yes, these are (partly) fixes for bison v3.7.4 which you get on a fresh `brew install bison`. The errors from OSX bison were much worse (a warning for that would have definitely saved me 15 minutes of confusion).

**Comment by eapache** [comment]
The first commit is straightforward enough, though I guess it would involve dropping support for some older bisons. The second commit is a total guess.

**Comment by BrianAker** [comment]
I had some more time to look at this. The change to lex causes a linking error on a couple of Linux distributions.
`undefined reference to `config_lex(CONFIG_STYPE*, void*)'`
I need to find a solution for that error.
I didn't find an answer for this issue the last time I tried to solve it... maybe today will be the lucky day :)

**Comment by BrianAker** [comment]
Were you using Apple's version flex?
If you run this you can determine the version:
`flex --version`

**Comment by eapache** [comment]
```
$ flex --version
flex 2.5.35 Apple(flex-32)
```

Though I'm not immediately seeing where flex gets invoked by the toolchain. The issues I ran into seemed to be in bison and then compiling the resulting c files?

**Comment by BrianAker** [comment]
Thank you!

**Pull request merged**
